SRCS +=
INCLUDES +=
LIBS +=
LDFLAGS +=
LDLIBS +=

# Wirepas libraries used
SHARED_DATA=yes
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=2

APP_PRINTING=yes

# Node configuration from build parameters (network address, channel, etc.)
# Override on make command line:  make ... node_address=0x...
