apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
